### ISSUE TITLE
Program Not Running

### ISSUE THREAD

**Issue by tobsmeks** [wasiejen/Free-Snap-Tap#1]
free_snap_tap.exe says "Free Snap Tap started" but not working in game. I also tried starting the program in terminal with "python ./free_snap_tap.py command" but got response  "[Errno 2] No such file or directory" message.

**Comment by tobsmeks** [comment]
An update on this I tried the program in overwatch and it works. However I was using it in Marvel Rivals at first and it was not working in there

**Comment by wasiejen** [comment]
Hello, thank you for testing out my little program. :-)

> "[Errno 2] No such file or directory"

Most likely the active/current directory of the terminal was not in the same folder as the .py file.

> I tried the program in overwatch and it works

Thanks for the info. :-)

> Marvel Rivals at first and it was not working in there

Only tested it in 3 Games so far. Maybe Marvel Rival handles input differently. 

Logically speaking it should not make a difference which game you use, because the program intercepts and supresses the original input - what the game gets is what the program is sending out as idealized input. If it works in one igame it should also work in others.

Possible causes to not work:
- Some games just have a acceleration time on movement changes and so there will be none or only a slight effect. 

- But if the programs works as intented there will never be 2 key presses of opposing keys at the same time. So if you press a+d and you character stands still, than the game most likely intercepts the input from your keyboard earlier than my program. xD

**Comment by wasiejen** [comment]
#Answer:

Seems to be also a general problem with linux or the implementation of pynput for linux. on Linux only full key event supression is supported and not selective supression of some key events, what I do with this program. So with the actual package used and the approach I have taken to implement this program, there will be no way to make it work on linux.

**Comment by wasiejen** [comment]
V0.37 Linux v1 version is online. 
Not yet tested on linux. theoretically it might work. :-)

Would be helpful for me if you could test it.

**Comment by wasiejen** [comment]
With V0.50 removal of any implementation to support linux - most of the functionality would not work because of the missing possibility to supress key events on linux in general.
