### ISSUE TITLE
Not working with numbers

### ISSUE THREAD

**Issue by tbeezy** [wasiejen/Free-Snap-Tap#17]
I'm adding a tab group with numbers, but trying to use it with any numbers doesn't work. Tried a combination of only numbers, and numbers and letters but has no effect. Letters work by itself.

**Comment by wasiejen** [comment]
Thanks for testing the program and reporting the bug.

The issue should be fixed now.

The code checked first if the input could be cast as an int and so interpreted the input directly as the vk_code for the key instead of looking up the vk_code in the dict for the string of the 'number' key. So the input '1' was directly intepreted as vk_code which is the left mouse button or '2' as the right mouse button. :-D
