### ISSUE TITLE
Move the `.exe` files to GitHub Releases

### ISSUE THREAD

**Issue by Some1and2-XC** [wasiejen/Free-Snap-Tap#19]
Please don't bundle binaries like this. If you need to you should be using GitHub releases to upload stuff like that. 

Also for dependencies, if you write a `requirements.txt` file it makes it easy for people (and bat scripts) to install all the dependencies for a project. Documentation for those can be found [here](https://pip.pypa.io/en/stable/reference/requirements-file-format/) (you basically add the name of all the packages to a file.) With a `requirements.txt` file you can just run `pip install -r requirements.txt` and you get all the dependencies in your python environment.

**Comment by wasiejen** [comment]
Hello and thanks for your suggestions.

Can you elaborate why the direct distribution of the executable should not be done?
What I gathered online suggest that to directly distribute an executable seems to be a question of trust and might be a problem if a dependency manager automatically loads from a repo and with that also loads the executables. Pls correct me if I am wrong or extend on this if needed. :-)

This repo is not or was not indented to be used in such a way. ^^

I moved the exe into the release and added the requirements.txt

best regards

**Comment by Some1and2-XC** [comment]
For sure! There's a few reasons that executables shouldn't be distributed like that.

Firstly version control keeps track of changes and when you bundle python applications there is a lot of overhead, if I remember correctly when I did this each bundle was ~300mb. This very often means that your binaries are going to be bigger than all the code combined by several orders of magnitude. This means cloning your repository is going to take longer in cloning because you pull down the entire history of a repo (unless you specify `--depth 1`, something generally only required on large repos.) When you put a file in a release, this has nothing to do with the actual git repo. This will get worse over time where old versions of your binary inflate your repo size without a meaningful reason.

Secondly sometimes making binary releases are hard. Linux binaries don't work on windows and windows binaries don't work on Linux (without emulators and stuff) and there are all kinds of different incompatible architectures. I saw some other issue where someone was looking at getting Linux support working. Even though it isn't supported if you clone the repo on Linux you still have this unusable windows binary cloned into your work directory. This makes development kind of awkward, (I suppose you're supposed to just leave the windows binary there? Do you make a second binary in the root directory when Linux is supported?)

Lastly I am of the belief that downloading binaries to run somewhat unchecked should be a rather deliberate decision. Binaries make it hard to check the work of the author. So having one downloaded when I clone the repository to me doesn't feel good.

Also a bad binary is a bad binary. Bad packages that have bad binaries are especially bad because they can reach a lot farther (for example NPM's lovely [left-pad](https://www.theregister.com/2016/03/23/npm_left_pad_chaos/) package.) Running anyone else binary should require trust. If everything is a bunch of python scripts and `.bat` files is a lot easier to trust than a `.exe` especially because if I don't I can just read all the code and figure out exactly what everything does.

Yes, running a binary as part of an install step is extra extra bad.

Best of luck though! This seems like a fun project!

**Comment by wasiejen** [comment]
Thank you for taking your time and the effort to describe it in such detail. It never occurred to me, that with every change of the executable there will be another copy of it in the history and that it would lead to an continuously further inflating size of the repository. Thanks for pointing that out - that is something I will keep in mind in the future. 👍

It makes sense that for Linux users it is just awkward to get exe files with a repo. Even if it is not intended to be used on Linux at all at the time. Maybe I should mention the incompatibility on Linux earlier in the readme or description. A Linux version is not planned at the moment, mainly because the key suppression is not working there and so only the tap groupings functionality could be realized. Maybe just as a fun exercise but I am not sure that there is really demand for it. I personally use it way more for key replacements than I use the tap groups at the moment. (And I am a bit scared of testing it for 2 different OS)

I understand Binaries can be bad :-). They are hard to check that they really just do what the rest of the source files in repo contain. Will use the releases as mentioned moving forward to offer these.

Thanks for the link to the left-pad article. Very interesting and a bit scary to see the fragility.

I learned something new and useful, so thanks again for your time. And best of luck to you too.👏
