### ISSUE TITLE
Wayland Support?

### ISSUE THREAD

**Issue by deddroid** [wasiejen/Free-Snap-Tap#2]
Hi, I'm trying this tool on linux on wayland and the script didnt work (pressing A and D togheter the hero just stop himself).
there is a way to make it works?

thanks in advice

**Comment by wasiejen** [comment]
Hello, thanks for trying it out and giving feedback.

The script needs to be run as root on Linux Systems due to the way the pynput library has to interact with the kernel to get and send key events.

Thats the only advice I can give on that, since I have no tested it on Linux.

I added a small update to the py file that will check for root permissions on systems that are not Windows based.

> https://pynput.readthedocs.io/en/latest/limitations.html

"When running under Wayland, the X server emulator Xwayland will usually run, providing limited functionality. Notably, you will only receive input events from applications running under this emulator."

**Comment by deddroid** [comment]
Hi wasiejen, thanks for your answer. I can confirm that the script must be run as root, but sadly didnt work on wayland. thanks for your try, really appricciate

**Comment by wasiejen** [comment]
Thanks for your Feedback. 
Maybe I might try another Implementation of the key event handling in the future, but right now I dont know what else to do. ^^

If you only need the snap-tap for the `A` und `D` keys than maybe have a look at:
> https://github.com/dotdon/QuickSwitch

**Comment by deddroid** [comment]
thanks for your attention to the issue. I'll try it. thanks man for your time!

**Comment by wasiejen** [comment]
#3 so there is an explanation why it will not work on linux with the actual implemention of this program. 
And Wayland might make it even more complicated to solve. :-D

Just for your info ^^
