### ISSUE TITLE
I can't figure it out

### ISSUE THREAD

**Issue by skeidGX** [wasiejen/Free-Snap-Tap#48]
I installed everything according to the instructions, I run free_snap_tap.exe and nothing happens, what should I do, what am I doing wrong?

**Comment by wasiejen** [comment]
Hello and thanks for the interest.
Can you add a bit more info on what windows version you are using? 
Or if there is any output in the command line what is shown? 

In general:
You don't need to install anything if you run the .exe file.
When run it should start a command line interface (cmd or powershell) and show a menu with the minimal settings for snap tap of the keys: a,d and w,s.
When you enter 1 and hit enter, it will open the new config file to edit via your default txt editor.
When in menu, hitting enter then starts the program with the minimal settings.
Explanations on how to configure your config file can be found in the readme on github.

**Comment by wasiejen** [comment]
@dvgmdvgm thanks for your continued interest. :-)

How did you use the argument?

I just reused the start arguments for usage with the config file. 
They should be applied before any arguments given in the config file like in the example below, but should work normally except for the focusapp start argument.

example: that works for me
```bash
<arg>-nomenu

# Tap Groups
a, d
w, s
# Rebinds
# Macros
```

I sometimes encounter the problem that I need to set FST into focus and hit enter multiple times until it works. It even shows that it is active but will not update active window information when changing windows. Haven't figured out for now what this bug is about. It it something like that for you?

**Comment by wasiejen** [comment]
> UPDATED:
> Need to put arg before focus parameter. Now it's work

That tracks. It will be applied with the focus group if it is put after the focus parameter. But for it to recognize the focus window it already needs to be started and is outside of the menu - so the argument is still applied but because it is already active it will not change anything. ^^
