### ISSUE TITLE
Key jamming

### ISSUE THREAD

**Issue by s0cra13s** [wasiejen/Free-Snap-Tap#5]
Hi, the script works fine exactly until you hold down the Alt key. It's easier to show it once than to try to describe it. https://youtu.be/f1ObuX5VLoY Starting at 0:11 I have already released the A key, but the script is still pressing it. You can solve this problem by pressing the A button again with the Alt key released

**Comment by wasiejen** [comment]
Thanks for the video. This is really helpful. will have a look :-D

**Comment by wasiejen** [comment]
So, good news is I can replicate it.
If I press alt he treats all keys in tap groups as if there where other keys. So whil holding alt, a,d,w,s in standard config will be ignored entirely.
So if you press a, hold it and then hold alt and release a, he will ne register the release of a, because he thinks it is another key.
Have to investigate why this is happening exactly.

**Comment by wasiejen** [comment]
Pls test newest release - it should work now. :-)

# Answer:

The Alt and Alt gr Keys change the msg value to differentiate between up and down press from 256 and 257 to 260 and 261 ... I tested nearly ever other key and no other key shows this behavior. Have jet to look it up why exactly this happens. Workaround is to check for both 256 and 260 for down and 157 and 261 for up.

Will follow up if I find out why this behaves this way.

**Comment by s0cra13s** [comment]
Everything is great! Thank you
