### ISSUE TITLE
Edited: BUG: currently not possible to run the program without a \<focus> group

### ISSUE THREAD

**Issue by moonbot32** [wasiejen/Free-Snap-Tap#59]
Traceback (most recent call last):
  File "C:\Users\lla\Downloads\새 폴더\free_snap_tap.py", line 2102, in <module>
    main()
  File "C:\Users\lla\Downloads\새 폴더\free_snap_tap.py", line 2057, in main
    if focus_thread.is_alive():
NameError: name 'focus_thread' is not defined. Did you mean: 'Focus_Thread'?

I have these errors

**Comment by wasiejen** [comment]
Hello @moonbot32,
which version of FST do you use? Do you use the exe or py file?
(Note to myself: Should probably include a version info in the files xD)

The current 1.0.4 has no focus_thread variable in the mentioned lines of code.
Can you test again with the current version and give feedback if the error still occurs?

best regards

**Comment by wasiejen** [comment]
I think I found the source of the error. 

I missed to test FST without any focus group defined in the config file. 
When no \<focus>*name* is defined then the focus_thread will not be started - so the error occurs. 

Will be fixed in the next version, so that it will be possible to run the program without a focus group and thus it will be possible again to test it while it is constantly active. 

as a workaround define at least one \<focus>*name of program* in your config and it should work when this window is active or when you overwrite it with manual toggle in context menu of the status indicator.

**Comment by wasiejen** [comment]
fixed in #62
